using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Collections.Immutable;
using System.Text;

namespace BlazorKit.Generators;

[Generator]
public sealed class ComponentGenerator : IIncrementalGenerator
{
    private const string ComponentAttribute = "BlazorKit.Generation.GenerateComponentAttribute";
    private const string PropertyAttribute = "BlazorKit.Generation.GeneratedPropertyAttribute";
    private const string EventAttribute = "BlazorKit.Generation.GeneratedEventAttribute";
    private const string NsView = "AppKit.NSView";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationAndAttributes = context.CompilationProvider.Select(static (compilation, _) =>
            (compilation, compilation.Assembly.GetAttributes()));

        context.RegisterSourceOutput(compilationAndAttributes, static (productionContext, source) =>
            Execute(productionContext, source.compilation, source.Item2));
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<AttributeData> assemblyAttributes)
    {
        var controls = assemblyAttributes
            .Where(attribute => attribute.AttributeClass?.ToDisplayString() == ComponentAttribute)
            .Select(attribute => ReadControl(attribute, compilation))
            .Where(control => control is not null)
            .Cast<ControlModel>()
            .ToList();

        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var control in controls)
        {
            if (!names.Add(control.Name))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateControl,
                    control.AttributeLocation,
                    control.Name));
                continue;
            }

            context.AddSource($"{control.Name}.g.cs", GenerateComponent(control, assemblyAttributes));
        }

        context.AddSource("GeneratedViewAdapterRegistrations.g.cs", GenerateRegistrations(controls));
    }

    private static ControlModel? ReadControl(AttributeData attribute, Compilation compilation)
    {
        var viewType = compilation.GetTypeByMetadataName(NsView);
        if (attribute.ConstructorArguments.FirstOrDefault().Value is not INamedTypeSymbol type || viewType is null || !InheritsFrom(type, viewType))
        {
            return null;
        }

        var isContainer = GetNamedBool(attribute, "IsContainer");
        var containerKind = GetNamedInt(attribute, "ContainerKind");
        var isValueAdapter = GetNamedBool(attribute, "IsValueAdapter");
        var valueType = GetNamedString(attribute, "ValueType");
        var valueProperty = GetNamedString(attribute, "ValueProperty");
        var valueChangedEvent = GetNamedString(attribute, "ValueChangedEvent");
        var constructorExpression = GetNamedString(attribute, "ConstructorExpression");
        var excludes = GetNamedStringArray(attribute, "ExcludeProperties");

        return new ControlModel(
            type,
            type.Name,
            isContainer,
            containerKind,
            isValueAdapter,
            valueType,
            valueProperty,
            valueChangedEvent,
            constructorExpression,
            excludes,
            attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation());
    }

    private static string GenerateComponent(ControlModel control, ImmutableArray<AttributeData> assemblyAttributes)
    {
        var properties = GetProperties(control).ToList();
        var events = GetEvents(control, assemblyAttributes).ToList();
        var aliases = GetPropertyAliases(control, assemblyAttributes).ToList();
        var valueEvent = events.FirstOrDefault(@event => @event.IsValueChanged);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace BlazorKit.Components;");
        source.AppendLine();
        source.AppendLine($"public sealed class {control.Name} : global::Microsoft.AspNetCore.Components.ComponentBase");
        source.AppendLine("{");
        foreach (var property in properties.Concat(aliases))
        {
            var initializer = property.IsReferenceType ? " = default!;" : string.Empty;
            source.AppendLine($"    [global::Microsoft.AspNetCore.Components.Parameter] public {property.TypeName} {property.ComponentName} {{ get; set; }}{initializer}");
        }

        if (control.IsContainer)
        {
            source.AppendLine("    [global::Microsoft.AspNetCore.Components.Parameter] public global::Microsoft.AspNetCore.Components.RenderFragment? ChildContent { get; set; }");
        }

        foreach (var @event in events)
        {
            source.AppendLine($"    [global::Microsoft.AspNetCore.Components.Parameter] public {@event.CallbackType} {@event.ComponentName} {{ get; set; }}");
        }

        source.AppendLine();
        source.AppendLine("    protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder)");
        source.AppendLine("    {");
        if (control.IsContainer)
        {
            source.AppendLine("        if (ChildContent is not null) builder.AddContent(0, ChildContent);");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine($"internal sealed class {control.Name}Adapter : global::BlazorKit.Components.Base.ViewAdapter<{control.TypeName}>");
        if (control.IsContainer) source.AppendLine(", global::BlazorKit.Abstractions.IViewContainer");
        if (control.IsValueAdapter) source.AppendLine($", global::BlazorKit.Abstractions.IValueAdapter<{control.ValueType ?? "object?"}>");
        source.AppendLine("{");

        foreach (var @event in events)
        {
            source.AppendLine($"    private {@event.CallbackType} _{@event.ComponentName};");
        }

        if (control.IsValueAdapter)
        {
            source.AppendLine("    private bool _updatingValue;");
        }

        var constructor = control.ConstructorExpression ?? FindConstructor(control.Type);
        source.AppendLine($"    public {control.Name}Adapter() : base({constructor})");
        if (events.Count > 0)
        {
            source.AppendLine("    {");
            foreach (var @event in events)
            {
                source.AppendLine($"        View.{@event.NativeName} += On{@event.NativeName};");
            }
            source.AppendLine("    }");
        }
        else source.AppendLine(" { }");

        source.AppendLine();
        source.AppendLine("    public override void ApplyParameters(global::Microsoft.AspNetCore.Components.ParameterView parameters)");
        source.AppendLine("    {");
        source.AppendLine("        foreach (var parameter in parameters)");
        source.AppendLine("        {");
        source.AppendLine("            switch (parameter.Name)");
        source.AppendLine("            {");
        foreach (var property in properties.Concat(aliases))
        {
            if (control.IsValueAdapter && property.NativeName == control.ValueProperty)
            {
                source.AppendLine($"                case nameof({control.Name}.{property.ComponentName}):");
                var valueExpression = control.ValueType == "string?"
                    ? "parameter.Value as string ?? string.Empty"
                    : $"parameter.Value is null ? default({property.NativeTypeName}) : ({property.NativeTypeName})parameter.Value";
                source.AppendLine($"                    var value = {valueExpression};");
                source.AppendLine("                    if (!EqualityComparer<" + property.NativeTypeName + ">.Default.Equals(View." + property.NativeName + ", value))");
                source.AppendLine("                    {");
                source.AppendLine("                        _updatingValue = true;");
                source.AppendLine($"                        View.{property.NativeName} = value!;");
                source.AppendLine("                        _updatingValue = false;");
                source.AppendLine("                    }");
                source.AppendLine("                    break;");
            }
            else
            {
                source.AppendLine($"                case nameof({control.Name}.{property.ComponentName}): View.{property.NativeName} = parameter.Value is null ? default! : ({property.NativeTypeName})parameter.Value; break;");
            }
        }
        foreach (var @event in events)
        {
            source.AppendLine($"                case nameof({control.Name}.{@event.ComponentName}) when parameter.Value is {@event.CallbackType} callback: _{@event.ComponentName} = callback; break;");
        }
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("    }");

        foreach (var @event in events)
        {
            if (@event.IsValueChanged)
            {
                source.AppendLine();
                source.AppendLine($"    private async void On{@event.NativeName}(object? sender, EventArgs e)");
                source.AppendLine("    {");
                source.AppendLine("        if (!_updatingValue)");
                source.AppendLine($"            await _{@event.ComponentName}.InvokeAsync(View.{control.ValueProperty});");
                source.AppendLine("    }");
            }
            else if (@event.EventArgumentType is null)
            {
                source.AppendLine();
                source.AppendLine($"    private async void On{@event.NativeName}(object? sender, EventArgs e) => await _{@event.ComponentName}.InvokeAsync();");
            }
            else
            {
                source.AppendLine();
                source.AppendLine($"    private async void On{@event.NativeName}(object? sender, {@event.EventArgumentType} e) => await _{@event.ComponentName}.InvokeAsync(e);");
            }
        }

        if (control.IsValueAdapter)
        {
            source.AppendLine();
            var valueAssignment = control.ValueType == "string?"
                ? $"value ?? string.Empty"
                : "value";
            source.AppendLine("    public void SetValue(" + control.ValueType + " value)");
            source.AppendLine("    {");
            source.AppendLine($"        var nextValue = {valueAssignment};");
            source.AppendLine($"        if (!EqualityComparer<{control.ValueType}>.Default.Equals(View.{control.ValueProperty}, nextValue))");
            source.AppendLine("        {");
            source.AppendLine("            _updatingValue = true;");
            source.AppendLine($"            View.{control.ValueProperty} = nextValue;");
            source.AppendLine("            _updatingValue = false;");
            source.AppendLine("        }");
            source.AppendLine("    }");
        }

        if (control.IsContainer)
        {
            source.AppendLine();
            source.AppendLine("    public void SetChildren(global::System.Collections.Generic.IReadOnlyList<global::BlazorKit.Abstractions.IViewAdapter> children)");
            source.AppendLine("    {");
            source.AppendLine("        foreach (var child in children) child.View.RemoveFromSuperview();");
            switch (control.ContainerKind)
            {
                case 1:
                    source.AppendLine("        foreach (var child in children) View.AddArrangedSubview(child.View);");
                    break;
                case 2:
                    source.AppendLine("        View.DocumentView = children.Count == 0 ? default! : children[0].View;");
                    break;
                case 3:
                    source.AppendLine("        View.ContentView = children.Count == 0 ? default! : children[0].View;");
                    break;
                default:
                    source.AppendLine("        foreach (var child in children) View.AddSubview(child.View);");
                    break;
            }
            source.AppendLine("    }");
        }

        source.AppendLine();
        source.AppendLine("    public override void Dispose()");
        source.AppendLine("    {");
        foreach (var @event in events)
        {
            source.AppendLine($"        View.{@event.NativeName} -= On{@event.NativeName};");
        }
        source.AppendLine("        base.Dispose();");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static IEnumerable<PropertyModel> GetProperties(ControlModel control)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var type = control.Type; type is not null; type = type.BaseType)
        {
            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (!seen.Add(property.Name) || property.IsStatic || property.IsIndexer || property.SetMethod?.DeclaredAccessibility != Accessibility.Public || control.Excludes.Contains(property.Name) || IsInfrastructureProperty(property.Name)) continue;
                yield return new PropertyModel(property.Name, property.Name, TypeName(property.Type), TypeName(property.Type), property.Type.IsReferenceType);
            }
        }
    }

    private static IEnumerable<PropertyModel> GetPropertyAliases(ControlModel control, ImmutableArray<AttributeData> attributes)
    {
        foreach (var attribute in attributes.Where(a => a.AttributeClass?.ToDisplayString() == PropertyAttribute))
        {
            if (attribute.ConstructorArguments.Length < 3 || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type || !SymbolEqualityComparer.Default.Equals(type, control.Type)) continue;
            var nativeName = (string)attribute.ConstructorArguments[1].Value!;
            var componentName = (string)attribute.ConstructorArguments[2].Value!;
            var property = control.Type.GetMembers(nativeName).OfType<IPropertySymbol>().FirstOrDefault(p => p.SetMethod is not null);
            if (property is not null) yield return new PropertyModel(nativeName, componentName, TypeName(property.Type), TypeName(property.Type), property.Type.IsReferenceType);
        }
    }

    private static IEnumerable<EventModel> GetEvents(ControlModel control, ImmutableArray<AttributeData> attributes)
    {
        var configured = attributes.Where(a => a.AttributeClass?.ToDisplayString() == EventAttribute)
            .Where(a => a.ConstructorArguments.Length >= 3 && a.ConstructorArguments[0].Value is INamedTypeSymbol type && SymbolEqualityComparer.Default.Equals(type, control.Type))
            .ToDictionary(a => (string)a.ConstructorArguments[1].Value!, a => a);

        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var type = control.Type; type is not null; type = type.BaseType)
        {
            foreach (var @event in type.GetMembers().OfType<IEventSymbol>())
            {
                if (!seen.Add(@event.Name) || @event.IsStatic) continue;
                var callbackName = configured.TryGetValue(@event.Name, out var configuredEvent)
                    ? (string)configuredEvent.ConstructorArguments[2].Value!
                    : @event.Name;
                var isValueChanged = configuredEvent is not null && GetNamedBool(configuredEvent, "IsValueChanged");
                if (!TryGetEventArgument(@event.Type, out var argumentType)) continue;
                var callbackType = isValueChanged
                    ? $"global::Microsoft.AspNetCore.Components.EventCallback<{control.ValueType}>"
                    : argumentType is null ? "global::Microsoft.AspNetCore.Components.EventCallback" : $"global::Microsoft.AspNetCore.Components.EventCallback<{argumentType}>";
                yield return new EventModel(@event.Name, callbackName, callbackType, argumentType, isValueChanged);
            }
        }
    }

    private static string GenerateRegistrations(IEnumerable<ControlModel> controls)
    {
        var source = new StringBuilder("// <auto-generated />\nnamespace BlazorKit;\n\ninternal static class GeneratedViewAdapterRegistrations\n{\n    public static void Register(ViewAdapterResolver resolver)\n    {\n");
        foreach (var control in controls) source.AppendLine($"        resolver.Register<global::BlazorKit.Components.{control.Name}, global::BlazorKit.Components.{control.Name}Adapter>();");
        source.AppendLine("    }\n}");
        return source.ToString();
    }

    private static string FindConstructor(INamedTypeSymbol type)
    {
        var rect = type.InstanceConstructors.FirstOrDefault(c => c.Parameters.Length == 1 && c.Parameters[0].Type.ToDisplayString() == "CoreGraphics.CGRect");
        if (rect is not null) return $"new {TypeName(type)}(global::CoreGraphics.CGRect.Empty)";
        return $"new {TypeName(type)}()";
    }

    private static bool TryGetEventArgument(ITypeSymbol type, out string? argumentType)
    {
        argumentType = null;
        if (type.ToDisplayString() == "System.EventHandler") return true;
        if (type is INamedTypeSymbol named && named.OriginalDefinition.ToDisplayString() == "System.EventHandler<TEventArgs>")
        {
            argumentType = TypeName(named.TypeArguments[0]);
            return true;
        }
        return false;
    }

    private static bool IsInfrastructureProperty(string name) => name is "ClassHandle" or "Handle" or "SuperHandle" or "Subviews" or "Superview" or "Window" or "WeakDelegate" or "Delegate" or "DataSource" or "ArrangedSubviews" or "ContentView" or "DocumentView";
    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType) => SymbolEqualityComparer.Default.Equals(type, baseType) || (type.BaseType is not null && InheritsFrom(type.BaseType, baseType));
    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static bool GetNamedBool(AttributeData data, string name) => data.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value is true;
    private static int GetNamedInt(AttributeData data, string name) => data.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value is int value ? value : 0;
    private static string? GetNamedString(AttributeData data, string name) => data.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value as string;
    private static ImmutableHashSet<string> GetNamedStringArray(AttributeData data, string name)
    {
        if (!data.NamedArguments.Any(argument => argument.Key == name)) return [];
        var value = data.NamedArguments.First(argument => argument.Key == name).Value;
        return value.Kind == TypedConstantKind.Array
            ? value.Values.Select(item => item.Value as string).Where(item => item is not null).Cast<string>().ToImmutableHashSet(StringComparer.Ordinal)
            : ImmutableHashSet<string>.Empty;
    }

    private sealed class ControlModel(INamedTypeSymbol type, string name, bool isContainer, int containerKind, bool isValueAdapter, string? valueType, string? valueProperty, string? valueChangedEvent, string? constructorExpression, ImmutableHashSet<string> excludes, Location? attributeLocation)
    {
        public INamedTypeSymbol Type { get; } = type;
        public string Name { get; } = name;
        public bool IsContainer { get; } = isContainer;
        public int ContainerKind { get; } = containerKind;
        public bool IsValueAdapter { get; } = isValueAdapter;
        public string? ValueType { get; } = valueType;
        public string? ValueProperty { get; } = valueProperty;
        public string? ValueChangedEvent { get; } = valueChangedEvent;
        public string? ConstructorExpression { get; } = constructorExpression;
        public ImmutableHashSet<string> Excludes { get; } = excludes;
        public Location? AttributeLocation { get; } = attributeLocation;
        public string TypeName => Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }
    private sealed class PropertyModel(string nativeName, string componentName, string typeName, string nativeTypeName, bool isReferenceType)
    {
        public string NativeName { get; } = nativeName;
        public string ComponentName { get; } = componentName;
        public string TypeName { get; } = typeName;
        public string NativeTypeName { get; } = nativeTypeName;
        public bool IsReferenceType { get; } = isReferenceType;
    }
    private sealed class EventModel(string nativeName, string componentName, string callbackType, string? eventArgumentType, bool isValueChanged)
    {
        public string NativeName { get; } = nativeName;
        public string ComponentName { get; } = componentName;
        public string CallbackType { get; } = callbackType;
        public string? EventArgumentType { get; } = eventArgumentType;
        public bool IsValueChanged { get; } = isValueChanged;
    }

    private static class Diagnostics
    {
        public static readonly DiagnosticDescriptor DuplicateControl = new("BKGEN001", "Duplicate generated component", "The component '{0}' was selected more than once", "BlazorKit", DiagnosticSeverity.Error, true);
    }
}
