using System.Text;

namespace BlazorKit.Generators;

internal static class ComponentSourceGenerator
{
    private static readonly IGenerationStrategy[] Strategies =
    [
        new PropertyGenerationStrategy(),
        new EventGenerationStrategy(),
        new ValueAdapterGenerationStrategy(),
        new ContainerGenerationStrategy()
    ];

    public static string Generate(GenerationContext context)
    {
        var active = Strategies.Where(strategy => strategy.AppliesTo(context)).ToArray();
        var control = context.Control;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace BlazorKit.Components;");
        source.AppendLine();
        source.AppendLine($"public sealed class {control.Name} : global::Microsoft.AspNetCore.Components.ComponentBase");
        source.AppendLine("{");
        foreach (var strategy in active) strategy.AppendComponentMembers(source, context);
        source.AppendLine();
        source.AppendLine("    protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder)");
        source.AppendLine("    {");
        if (control.IsContainer) source.AppendLine("        if (ChildContent is not null) builder.AddContent(0, ChildContent);");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine($"internal sealed class {control.Name}Adapter : global::BlazorKit.Components.Base.ViewAdapter<{control.TypeName}>");
        if (control.IsContainer) source.AppendLine(", global::BlazorKit.Abstractions.IViewContainer");
        if (control.IsValueAdapter) source.AppendLine($", global::BlazorKit.Abstractions.IValueAdapter<{control.ValueType ?? "object?"}>");
        source.AppendLine("{");
        foreach (var strategy in active) strategy.AppendAdapterFields(source, context);
        AppendConstructor(source, context);
        AppendApplyParameters(source, context, active);
        foreach (var strategy in active) strategy.AppendAdapterMembers(source, context);
        source.AppendLine();
        source.AppendLine("    public override void Dispose()");
        source.AppendLine("    {");
        foreach (var strategy in active) strategy.AppendDispose(source, context);
        source.AppendLine("        base.Dispose();");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendConstructor(StringBuilder source, GenerationContext context)
    {
        var control = context.Control;
        var constructor = control.ConstructorExpression ?? SymbolUtilities.FindConstructor(control.Type);
        source.AppendLine($"    public {control.Name}Adapter() : base({constructor})");
        if (context.Events.Count == 0)
        {
            source.AppendLine(" { }");
            return;
        }

        source.AppendLine("    {");
        foreach (var @event in context.Events) source.AppendLine($"        View.{@event.NativeName} += On{@event.NativeName};");
        source.AppendLine("    }");
    }

    private static void AppendApplyParameters(StringBuilder source, GenerationContext context, IGenerationStrategy[] strategies)
    {
        var control = context.Control;
        source.AppendLine();
        source.AppendLine("    public override void ApplyParameters(global::Microsoft.AspNetCore.Components.ParameterView parameters)");
        source.AppendLine("    {");
        source.AppendLine("        foreach (var parameter in parameters)");
        source.AppendLine("        {");
        source.AppendLine("            switch (parameter.Name)");
        source.AppendLine("            {");
        foreach (var strategy in strategies) strategy.AppendApplyParameterCases(source, context);
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }
}

internal static class RegistrationSourceGenerator
{
    public static string Generate(IEnumerable<ControlModel> controls)
    {
        var source = new StringBuilder("// <auto-generated />\nnamespace BlazorKit;\n\ninternal static class GeneratedViewAdapterRegistrations\n{\n    public static void Register(ViewAdapterResolver resolver)\n    {\n");
        foreach (var control in controls)
            source.AppendLine($"        resolver.Register<global::BlazorKit.Components.{control.Name}, global::BlazorKit.Components.{control.Name}Adapter>();");
        source.AppendLine("    }\n}");
        return source.ToString();
    }
}
