<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <ApplicationId>com.blazorappkit.sample</ApplicationId>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>
    <IsMacOSApp>true</IsMacOSApp>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../BlazorAppKit/BlazorAppKit.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <Content Remove="**/*.razor" />
    <RazorComponent Include="**/*.razor" />
  </ItemGroup>
</Project>
