<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);BL0006</NoWarn>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
    <PackageId>BlazorAppKit</PackageId>
    <Authors>Sathiyaraman-M</Authors>
    <Description>Build native macOS applications with Blazor and AppKit.</Description>
    <PackageTags>blazor;macos;appkit;native;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Sathiyaraman-M/BlazorAppKit</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="README.md" />
    <None Include="../../LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Include="../BlazorAppKit.Generators/bin/$(Configuration)/net10.0/BlazorAppKit.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <ProjectReference Include="../BlazorAppKit.Generators/BlazorAppKit.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="AddReferenceDocumentationFiles" BeforeTargets="CoreCompile">
    <ItemGroup>
      <_ReferenceDocumentation Include="@(ReferencePath)">
        <DocumentationPath>%(RootDir)%(Directory)%(Filename).xml</DocumentationPath>
      </_ReferenceDocumentation>
      <AdditionalFiles Include="@(_ReferenceDocumentation->'%(DocumentationPath)')"
                       Condition="Exists('%(DocumentationPath)')" />
    </ItemGroup>
  </Target>
</Project>
