<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);BL0006</NoWarn>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
    <PackageId>BlazorKit</PackageId>
    <Authors>Sathiyaraman-M</Authors>
    <Description>Build native macOS applications with Blazor and AppKit.</Description>
    <PackageTags>blazor;macos;appkit;native;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Sathiyaraman-M/BlazorKit</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="README.md" />
    <None Include="../../LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Include="../BlazorKit.Generators/bin/$(Configuration)/net10.0/BlazorKit.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <ProjectReference Include="../BlazorKit.Generators/BlazorKit.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
