<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageType>Template</PackageType>
    <PackageId>BlazorKit.Templates</PackageId>
    <Authors>Sathiyaraman-M</Authors>
    <Description>Project templates for native macOS applications built with BlazorKit.</Description>
    <PackageTags>dotnet-new;template;blazor;macos;appkit</PackageTags>
    <RepositoryUrl>https://github.com/Sathiyaraman-M/BlazorKit</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <NoBuild>true</NoBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <None Include="../../LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Include="template/**/*" Pack="true" PackagePath="content/" />
  </ItemGroup>
</Project>
